repos:
- hooks:
  - id: black
  repo: https://github.com/ambv/black
  rev: 22.1.0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
- hooks:
  - id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
- hooks:
  - id: nbstripout
  repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
- hooks:
  - args:
    - --ignore-missing-imports
    - --namespace-packages
    - --explicit-package-bases
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.941
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
