name: process_2
keep_columns:
    - Income
    - Recency
    - NumWebVisitsMonth
    - Complain
    - age
    - total_purchases
    - enrollment_years
    - family_size

remove_outliers_threshold:
  age: 90
  Income: 600000

family_size:
  Married: 2
  Together: 2
  Absurd: 1
  Widow: 1
  YOLO: 1
  Divorced: 1
  Single: 1
  Alone: 1

